simulation_settings:

  # Choose how to define simulation duration:
  # Options: "date_range", "seasonal", "full_year"
  simulation_mode: "full_year"


  # The start date of the simulation (format: "YYYY-MM-DD").
  # Example: "2020-01-01" will simulate from January 1st, 2020.
  date_start: "2020-01-01"
  
  # The end date of the simulation (format: "YYYY-MM-DD").
  # Example: "2020-12-31" will simulate until December 31st, 2020.
  date_end: "2020-12-31"
  
  #Calibration factor
  peak_enlarge: 0.15

  # The folder where the simulation results will be saved.
  # Example: "output" will save the results in a folder named "output".
  output_folder: 'output'
  parallel: false

  # The number of days for each season in the simulation. You can specify different values for each season.
  days_per_season:
    summer: 90  # Specify number of days for the summer season
    winter: 90  # Specify number of days for the winter season
    spring: 90   # Specify number of days for the spring season
    autumn: 90  # Specify number of days for the autumn season
    
  regions:
    - lowlands
    - highlands
    - valleys
    - raqaypampa

  # A list of seasons to simulate. You can add more seasons (e.g., spring, summer) or modify them.
  # Example: ["summer", "winter", "spring", "autumn"] defines four seasons.
  seasons:
    - summer
    - winter
    - spring
    - fall
   
  # Simulation levels determine at which level the simulation will run. 
  # Options: "energy_service" (individual services like lighting, refrigeration),
  # "user_type" (low_consumption, high_consumption users), 
  # "sector" (households, community services, income-generating activities),
  # "community" (full community simulation including all sectors).
  simulation_levels:
    - energy_service
    - sector
    - user_type
    - community

  sectors:  # The sectors involved in the simulation. Each sector contains different user types and their energy services.
    household:
        high_consumption:  # Household sector: Contains different user types based on consumption level.
        count: 1   # 'count' defines how many high-consumption households to simulate.
            energy_service:   # 'energy_service' lists the energy services available for this user type.
                              # Example: ["illumination", "refrigeration", "ict"] for high consumption households.
              - illumination
              - ICT
              - cold_storage
              - space_cooling
              - space_heating
              - water_heating
        low_consumption:
        count: 1
            energy_service:
              - illumination
              - ICT
              - cold_storage
              - space_cooling
              - space_heating
              - water_heating
         
        energy_sufficiency:
        count: 50
                energy_service:
                  - illumination
                  - ICT
                  - cold_storage
                  - space_cooling
                  - space_heating
                  - water_heating
        
    community_services:   # Community services sector: Includes community services like schools, health posts, etc.
        small_school:
        count: 1
            energy_service:
                - illumination
                - ICT
                - cold_storage
                - space_cooling
                - space_heating
                - water_heating
                
        medium_school:
        count: 1
            energy_service:
                - illumination
                - ICT
                - cold_storage
                - space_cooling
                - space_heating
                - water_heating
                
        big_school:
        count: 1
            energy_service:
                - illumination
                - ICT
                - cold_storage
                - space_cooling
                - space_heating
                - water_heating
        health_post:
        count: 1
            energy_service: 
                - illumination
                - ICT
                - cold_storage
                - space_cooling
                - space_heating
                - water_heating
                - medical_equip
        health_center:
        count: 1
            energy_service: 
                - illumination
                - ICT
                - cold_storage
                - space_cooling
                - space_heating
                - water_heating
                - medical_equip
                - water_supply
        public_lighting:
        count: 1
            energy_service: 
                - illumination
            
    income_generating_activity:    # Income generating activities sector: Includes stores, workshops, etc.
        workshop:
        count: 1
            energy_service:
                - illumination
                - ICT
                - cold_storage
                - space_cooling
                - space_heating
                - water_heating
                - machinery
        store:
        count: 1
            energy_service:
                - illumination
                - ICT
                - cold_storage
                - space_cooling
                - space_heating
                - water_heating
        entertainment_business:
        count: 1
            energy_service:
                - cold_storage
                - ICT
                - illumination
        flour_processing:
        count: 1
            energy_service:
                - flour_processing
        restaurant:
        count: 1
            energy_service:
                - cold_storage
                - illumination  
                - kitchen
        store:
        count: 1
            energy_service:
                - cold_storage
                - ICT
                - illumination
        milk_production:
        count: 1
          energy_service:
            - milk_production




             
        
