#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 21 12:42:19 2023

@author: claudia
"""

import csv
import json

csv_file = 'base_data_v2.csv'

# Initialize an empty list to store the CSV data
csv_data = []

# Read the CSV file and store its contents in csv_data
with open(csv_file, 'r') as file:
    csv_reader = csv.DictReader(file)
    for row in csv_reader:
        csv_data.append(row)

# Convert the CSV data to JSON
json_data = json.dumps(csv_data, indent=4)

# Save JSON data to a file (optional)
json_file = 'data.json'
with open(json_file, 'w') as file:
    file.write(json_data)